/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package easypower;

/**
 *
 * @author shitu
 */

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
public class AdminProfile extends javax.swing.JFrame {
    
    String username;
    String firstname;
    String lastname;
    String usertype;
    String cardholder_t;
    int userid;

    /**
     * Creates new form AdminProfile
     */
    public AdminProfile(int u_id_temp) {
        initComponents();
        userid = u_id_temp;
        
        
        try { 
           
           String url="jdbc:sqlserver://localhost:1433;databaseName=easypower;user=shitul;password=tnb";
           
           Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
             Connection con=DriverManager.getConnection(url);
           String sql= "SELECT * FROM users WHERE u_id="+userid; 
            PreparedStatement pst=con.prepareStatement(sql);
            //pst.executeUpdate();
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
            firstname = rs.getString("f_name");
            lastname = rs.getString("l_name");
            usertype = rs.getString("u_type");
            username = rs.getString("u_name");
            cardholder_t = rs.getString("cardholder");
            
           
            
            String name_temp = firstname+" "+lastname;
            name_lebel.setText(name_temp);
            u_type_lebel.setText(usertype);
            name_of_user.setText(name_temp);
            User_name_of_user.setText(username);
            user_type_of_user.setText(usertype);
        
            f_name_in.setText(firstname);
            l_name_in.setText(lastname);
            u_name_in.setText(username);
            jPasswordField1.setText(rs.getString("pass_1"));
            jPasswordField2.setText(rs.getString("pass_2"));
            } else {
                JOptionPane.showMessageDialog(null, "Error");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Signup.class.getName()).log(Level.SEVERE, null, ex);
             
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Signup.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
    }

    private AdminProfile() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        name_lebel = new javax.swing.JLabel();
        u_type_lebel = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        send_bill2 = new javax.swing.JButton();
        send_notification1 = new javax.swing.JButton();
        send_notification2 = new javax.swing.JButton();
        send_notification = new javax.swing.JButton();
        send_notification3 = new javax.swing.JButton();
        send_notification5 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        name_of_user = new javax.swing.JLabel();
        User_name_of_user = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        user_type_of_user = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        f_name_in = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        l_name_in = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        u_name_in = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        jPasswordField2 = new javax.swing.JPasswordField();
        jButton9 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(73, 175, 204));

        name_lebel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        name_lebel.setForeground(new java.awt.Color(255, 255, 255));
        name_lebel.setText("f_name");

        u_type_lebel.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        u_type_lebel.setForeground(new java.awt.Color(255, 255, 255));
        u_type_lebel.setText("u_type");

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 51, 51));
        jButton2.setText("LOGOUT");
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        send_bill2.setBackground(new java.awt.Color(67, 162, 196));
        send_bill2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        send_bill2.setForeground(new java.awt.Color(255, 255, 255));
        send_bill2.setText("Send Bill");
        send_bill2.setAlignmentY(0.0F);
        send_bill2.setBorder(null);
        send_bill2.setBorderPainted(false);
        send_bill2.setContentAreaFilled(false);
        send_bill2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        send_bill2.setFocusable(false);
        send_bill2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                send_bill2ActionPerformed(evt);
            }
        });

        send_notification1.setBackground(new java.awt.Color(67, 162, 196));
        send_notification1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        send_notification1.setForeground(new java.awt.Color(255, 255, 255));
        send_notification1.setText("Edit Profile");
        send_notification1.setAlignmentY(0.0F);
        send_notification1.setBorder(null);
        send_notification1.setBorderPainted(false);
        send_notification1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        send_notification1.setFocusable(false);
        send_notification1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                send_notification1ActionPerformed(evt);
            }
        });

        send_notification2.setBackground(new java.awt.Color(67, 162, 196));
        send_notification2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        send_notification2.setForeground(new java.awt.Color(255, 255, 255));
        send_notification2.setText("View Profile");
        send_notification2.setAlignmentY(0.0F);
        send_notification2.setBorder(null);
        send_notification2.setBorderPainted(false);
        send_notification2.setContentAreaFilled(false);
        send_notification2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        send_notification2.setFocusable(false);
        send_notification2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                send_notification2ActionPerformed(evt);
            }
        });

        send_notification.setBackground(new java.awt.Color(67, 162, 196));
        send_notification.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        send_notification.setForeground(new java.awt.Color(255, 255, 255));
        send_notification.setText("Send Notification");
        send_notification.setAlignmentY(0.0F);
        send_notification.setBorder(null);
        send_notification.setBorderPainted(false);
        send_notification.setContentAreaFilled(false);
        send_notification.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        send_notification.setFocusable(false);
        send_notification.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                send_notificationActionPerformed(evt);
            }
        });

        send_notification3.setBackground(new java.awt.Color(67, 162, 196));
        send_notification3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        send_notification3.setForeground(new java.awt.Color(255, 255, 255));
        send_notification3.setText("Salary");
        send_notification3.setAlignmentY(0.0F);
        send_notification3.setBorder(null);
        send_notification3.setBorderPainted(false);
        send_notification3.setContentAreaFilled(false);
        send_notification3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        send_notification3.setFocusable(false);
        send_notification3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                send_notification3ActionPerformed(evt);
            }
        });

        send_notification5.setBackground(new java.awt.Color(67, 162, 196));
        send_notification5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        send_notification5.setForeground(new java.awt.Color(255, 255, 255));
        send_notification5.setText("Help");
        send_notification5.setAlignmentY(0.0F);
        send_notification5.setBorder(null);
        send_notification5.setBorderPainted(false);
        send_notification5.setContentAreaFilled(false);
        send_notification5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        send_notification5.setFocusable(false);
        send_notification5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                send_notification5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(send_bill2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(name_lebel))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(jButton2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(u_type_lebel)))
                        .addGap(0, 50, Short.MAX_VALUE))
                    .addComponent(send_notification, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(send_notification1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(send_notification2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(send_notification3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(send_notification5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(name_lebel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(u_type_lebel)
                .addGap(11, 11, 11)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(send_bill2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(send_notification1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(send_notification2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(send_notification, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(send_notification3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(send_notification5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(162, 162, 162))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Add Card");

        name_of_user.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        name_of_user.setText("Name");

        User_name_of_user.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        User_name_of_user.setText("u_name");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel2.setText("@");

        user_type_of_user.setText("user_type");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("First Name :");

        f_name_in.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        f_name_in.setText("f_name");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Last Name :");

        l_name_in.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        l_name_in.setText("l_name");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("User Name :");

        u_name_in.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        u_name_in.setText("u_name");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Password :");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Confirm Password :");

        jButton9.setBackground(new java.awt.Color(67, 162, 196));
        jButton9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("UPDATE");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(108, 108, 108)
                                .addComponent(jButton9))
                            .addComponent(name_of_user)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(User_name_of_user))
                            .addComponent(user_type_of_user))
                        .addGap(30, 30, 30)
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(78, 78, 78)
                        .addComponent(f_name_in, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(u_name_in, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                            .addComponent(jPasswordField1)
                            .addComponent(jPasswordField2)
                            .addComponent(l_name_in))))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(name_of_user)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(User_name_of_user))
                .addGap(4, 4, 4)
                .addComponent(user_type_of_user)
                .addGap(73, 73, 73)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(f_name_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(l_name_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(u_name_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(91, 91, 91)
                .addComponent(jButton9)
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new Login().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        try {
            String url="jdbc:sqlserver://localhost:1433;databaseName=easypower;user=shitul;password=tnb";
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection con=DriverManager.getConnection(url);
            String sql_1= "select u_name from users where u_name=?";
            PreparedStatement pst=con.prepareStatement(sql_1);
            pst.setString(1,u_name_in.getText());
            ResultSet rs = pst.executeQuery();

            String a = jPasswordField1.getText();
            String b = jPasswordField2.getText();
            if (!a.equals(b)) {
                JOptionPane.showMessageDialog(null, "Password dosen't match. Please re enter");
            }
            else if(rs.next() && !rs.getString("u_name").equals(username)){
                JOptionPane.showMessageDialog(null, "Username already taken. Please try another onle.");
            }
            else{
                url="jdbc:sqlserver://localhost:1433;databaseName=easypower;user=shitul;password=tnb";

                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                con=DriverManager.getConnection(url);
                String sql= "UPDATE users SET f_name=?,l_name=?,u_name=?,pass_1=?,pass_2=? WHERE u_id="+userid;
                pst=con.prepareStatement(sql);
                pst.setString(1,f_name_in.getText());
                pst.setString(2,l_name_in.getText());
                pst.setString(3,u_name_in.getText());
                pst.setString(4,jPasswordField1.getText());
                pst.setString(5,jPasswordField2.getText());
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "Profile Updated successfully!");
            }

        } catch (SQLException ex) {
            Logger.getLogger(Signup.class.getName()).log(Level.SEVERE, null, ex);

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Signup.class.getName()).log(Level.SEVERE, null, ex);
        }

        new Profile(userid).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void send_bill2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_send_bill2ActionPerformed
        // TODO add your handling code here:
        new AdminHome(userid).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_send_bill2ActionPerformed

    private void send_notification1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_send_notification1ActionPerformed
        // TODO add your handling code here:
        new AdminProfile(userid).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_send_notification1ActionPerformed

    private void send_notification2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_send_notification2ActionPerformed
        // TODO add your handling code here:
        new AdminProfileView(userid).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_send_notification2ActionPerformed

    private void send_notificationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_send_notificationActionPerformed
        // TODO add your handling code here:
        new SendNotification(userid).setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_send_notificationActionPerformed

    private void send_notification3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_send_notification3ActionPerformed
        // TODO add your handling code here:
        new Salary(userid).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_send_notification3ActionPerformed

    private void send_notification5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_send_notification5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_send_notification5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminProfile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel User_name_of_user;
    private javax.swing.JTextField f_name_in;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JTextField l_name_in;
    private javax.swing.JLabel name_lebel;
    private javax.swing.JLabel name_of_user;
    private javax.swing.JButton send_bill2;
    private javax.swing.JButton send_notification;
    private javax.swing.JButton send_notification1;
    private javax.swing.JButton send_notification2;
    private javax.swing.JButton send_notification3;
    private javax.swing.JButton send_notification4;
    private javax.swing.JButton send_notification5;
    private javax.swing.JTextField u_name_in;
    private javax.swing.JLabel u_type_lebel;
    private javax.swing.JLabel user_type_of_user;
    // End of variables declaration//GEN-END:variables
}
