/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package easypower;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Noor
 */
public class AdminHelp extends javax.swing.JFrame {

    /**
     * Creates new form AdminHelp
     */
    
    String firstname;
    String lastname;
    String usertype;
    String username;
    String cardholder_t;
    int userid;
    
    public AdminHelp(int userid) {
        initComponents();
        
        this.userid = userid;
        
        
        
        try { 
           
           String url="jdbc:sqlserver://localhost:1433;databaseName=easypower;user=shitul;password=tnb";
           
           Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
           Connection con=DriverManager.getConnection(url);
           String sql= "SELECT * FROM users WHERE u_id="+userid; 
            PreparedStatement pst=con.prepareStatement(sql);
            //pst.executeUpdate();
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
            firstname = rs.getString("f_name");
            lastname = rs.getString("l_name");
            usertype = rs.getString("u_type");
            username = rs.getString("u_name");
            cardholder_t = rs.getString("cardholder");
            
            
            
            String name_temp = firstname+" "+lastname;
            name_lebel.setText(name_temp);
            u_type_lebel.setText(usertype);
               
               
            }
        } catch (SQLException ex) {
            Logger.getLogger(Signup.class.getName()).log(Level.SEVERE, null, ex);
             
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Signup.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private AdminHelp() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        name_lebel = new javax.swing.JLabel();
        u_type_lebel = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        send_bill = new javax.swing.JButton();
        send_notification1 = new javax.swing.JButton();
        send_notification2 = new javax.swing.JButton();
        send_notification = new javax.swing.JButton();
        send_notification3 = new javax.swing.JButton();
        send_notification4 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(73, 175, 204));

        name_lebel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        name_lebel.setForeground(new java.awt.Color(255, 255, 255));
        name_lebel.setText("f_name");

        u_type_lebel.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        u_type_lebel.setForeground(new java.awt.Color(255, 255, 255));
        u_type_lebel.setText("u_type");

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 51, 51));
        jButton2.setText("LOGOUT");
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        send_bill.setBackground(new java.awt.Color(67, 162, 196));
        send_bill.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        send_bill.setForeground(new java.awt.Color(255, 255, 255));
        send_bill.setText("Send Bill");
        send_bill.setAlignmentY(0.0F);
        send_bill.setBorder(null);
        send_bill.setBorderPainted(false);
        send_bill.setContentAreaFilled(false);
        send_bill.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        send_bill.setFocusable(false);
        send_bill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                send_billActionPerformed(evt);
            }
        });

        send_notification1.setBackground(new java.awt.Color(67, 162, 196));
        send_notification1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        send_notification1.setForeground(new java.awt.Color(255, 255, 255));
        send_notification1.setText("Edit Profile");
        send_notification1.setAlignmentY(0.0F);
        send_notification1.setBorder(null);
        send_notification1.setBorderPainted(false);
        send_notification1.setContentAreaFilled(false);
        send_notification1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        send_notification1.setFocusable(false);
        send_notification1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                send_notification1ActionPerformed(evt);
            }
        });

        send_notification2.setBackground(new java.awt.Color(67, 162, 196));
        send_notification2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        send_notification2.setForeground(new java.awt.Color(255, 255, 255));
        send_notification2.setText("View Profile");
        send_notification2.setAlignmentY(0.0F);
        send_notification2.setBorder(null);
        send_notification2.setBorderPainted(false);
        send_notification2.setContentAreaFilled(false);
        send_notification2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        send_notification2.setFocusable(false);
        send_notification2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                send_notification2ActionPerformed(evt);
            }
        });

        send_notification.setBackground(new java.awt.Color(67, 162, 196));
        send_notification.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        send_notification.setForeground(new java.awt.Color(255, 255, 255));
        send_notification.setText("Send Notification");
        send_notification.setAlignmentY(0.0F);
        send_notification.setBorder(null);
        send_notification.setBorderPainted(false);
        send_notification.setContentAreaFilled(false);
        send_notification.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        send_notification.setFocusable(false);
        send_notification.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                send_notificationActionPerformed(evt);
            }
        });

        send_notification3.setBackground(new java.awt.Color(67, 162, 196));
        send_notification3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        send_notification3.setForeground(new java.awt.Color(255, 255, 255));
        send_notification3.setText("Salary");
        send_notification3.setAlignmentY(0.0F);
        send_notification3.setBorder(null);
        send_notification3.setBorderPainted(false);
        send_notification3.setContentAreaFilled(false);
        send_notification3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        send_notification3.setFocusable(false);
        send_notification3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                send_notification3ActionPerformed(evt);
            }
        });

        send_notification4.setBackground(new java.awt.Color(67, 162, 196));
        send_notification4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        send_notification4.setForeground(new java.awt.Color(255, 255, 255));
        send_notification4.setText("Help");
        send_notification4.setAlignmentY(0.0F);
        send_notification4.setBorder(null);
        send_notification4.setBorderPainted(false);
        send_notification4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        send_notification4.setFocusable(false);
        send_notification4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                send_notification4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(name_lebel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jButton2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(u_type_lebel)))
                .addContainerGap(60, Short.MAX_VALUE))
            .addComponent(send_notification4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(send_notification3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(send_bill, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(send_notification, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(send_notification1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(send_notification2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(name_lebel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(u_type_lebel)
                .addGap(11, 11, 11)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 187, Short.MAX_VALUE)
                .addComponent(send_notification3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(send_notification4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(134, 134, 134))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(170, 170, 170)
                    .addComponent(send_bill, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(send_notification1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(send_notification2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(send_notification, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(204, Short.MAX_VALUE)))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Add Card");

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 153, 255));
        jButton1.setText("Show case form");
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(51, 153, 255));
        jButton3.setText("Employee acticity form");
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(51, 153, 255));
        jButton4.setText("Apply for loan");
        jButton4.setContentAreaFilled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(51, 153, 255));
        jButton5.setText("Apply for bonous");
        jButton5.setContentAreaFilled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(257, 257, 257)
                .addComponent(jLabel1)
                .addContainerGap(83, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(135, 135, 135))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addGap(114, 114, 114))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addGap(140, 140, 140))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addGap(131, 131, 131))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(60, 60, 60)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4)
                .addGap(18, 18, 18)
                .addComponent(jButton5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new Login().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void send_billActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_send_billActionPerformed
        // TODO add your handling code here:
        new AdminHome(userid).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_send_billActionPerformed

    private void send_notification1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_send_notification1ActionPerformed
        // TODO add your handling code here:
        new AdminProfile(userid).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_send_notification1ActionPerformed

    private void send_notification2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_send_notification2ActionPerformed
        // TODO add your handling code here:
        new AdminProfileView(userid).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_send_notification2ActionPerformed

    private void send_notificationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_send_notificationActionPerformed
        // TODO add your handling code here:
        new SendNotification(userid).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_send_notificationActionPerformed

    private void send_notification3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_send_notification3ActionPerformed
        // TODO add your handling code here:
        new Salary(userid).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_send_notification3ActionPerformed

    private void send_notification4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_send_notification4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_send_notification4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Go to office and Contact Incharge.");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Go to office and Contact Incharge.");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Go to Account office and Contact Incharge.");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Go to Account office and Contact Incharge.");
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminHelp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminHelp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminHelp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminHelp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminHelp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel name_lebel;
    private javax.swing.JButton send_bill;
    private javax.swing.JButton send_notification;
    private javax.swing.JButton send_notification1;
    private javax.swing.JButton send_notification2;
    private javax.swing.JButton send_notification3;
    private javax.swing.JButton send_notification4;
    private javax.swing.JLabel u_type_lebel;
    // End of variables declaration//GEN-END:variables
}
