/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package easypower;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Noor
 */
public class Signup extends javax.swing.JFrame {
    
    

    /** 
     * Creates new form Signup
     */
    public Signup() {
        initComponents();
        f_name.setBackground(new java.awt.Color(255, 255, 255, 120));
        l_name.setBackground(new java.awt.Color(255, 255, 255, 120));
        age.setBackground(new java.awt.Color(255, 255, 255, 120));
        address.setBackground(new java.awt.Color(255, 255, 255, 120));
        post_no.setBackground(new java.awt.Color(255, 255, 255, 120));
        u_name.setBackground(new java.awt.Color(255, 255, 255, 120));
        pass_1.setBackground(new java.awt.Color(255, 255, 255, 120));
        pass_2.setBackground(new java.awt.Color(255, 255, 255, 120));
        u_type.setBackground(new java.awt.Color(255, 255, 255, 120));
        cardholder.setBackground(new java.awt.Color(255, 255, 255, 120));
        meter_number.setBackground(new java.awt.Color(255, 255, 255, 120));
        cardnumber.setBackground(new java.awt.Color(255, 255, 255, 120));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cardholder = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cardnumber = new javax.swing.JTextField();
        meter_number = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        pass_1 = new javax.swing.JPasswordField();
        pass_2 = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        u_type = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        u_name = new javax.swing.JTextField();
        post_no = new javax.swing.JTextField();
        l_name = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        age = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        f_name = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        cardholder.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cardholder.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "yes", "no" }));
        cardholder.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cardholderItemStateChanged(evt);
            }
        });
        cardholder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardholderActionPerformed(evt);
            }
        });
        jPanel1.add(cardholder);
        cardholder.setBounds(440, 340, 60, 30);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Already have an account?");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(200, 430, 160, 20);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("I am am a card holder");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(300, 350, 140, 14);

        cardnumber.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cardnumber.setForeground(new java.awt.Color(255, 255, 255));
        cardnumber.setBorder(javax.swing.BorderFactory.createTitledBorder("CARD NUMBER"));
        jPanel1.add(cardnumber);
        cardnumber.setBounds(290, 210, 140, 50);

        meter_number.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        meter_number.setForeground(new java.awt.Color(255, 255, 255));
        meter_number.setBorder(javax.swing.BorderFactory.createTitledBorder("Meter Number"));
        meter_number.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel1.add(meter_number);
        meter_number.setBounds(140, 210, 130, 50);

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(102, 204, 255));
        jButton2.setText("Login");
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(350, 430, 70, 21);

        pass_1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pass_1.setForeground(new java.awt.Color(255, 255, 255));
        pass_1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Password", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.add(pass_1);
        pass_1.setBounds(70, 270, 200, 50);

        pass_2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pass_2.setForeground(new java.awt.Color(255, 255, 255));
        pass_2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Confirm Password", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.add(pass_2);
        pass_2.setBounds(290, 270, 200, 50);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("I am am a");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(70, 350, 80, 14);

        u_type.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        u_type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Consumer", "Admin" }));
        jPanel1.add(u_type);
        u_type.setBounds(140, 340, 130, 30);

        jButton1.setBackground(new java.awt.Color(0, 153, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("SIGNUP");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(260, 400, 80, 30);

        u_name.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        u_name.setForeground(new java.awt.Color(255, 255, 255));
        u_name.setBorder(javax.swing.BorderFactory.createTitledBorder("USERNAME"));
        u_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                u_nameActionPerformed(evt);
            }
        });
        jPanel1.add(u_name);
        u_name.setBounds(210, 130, 170, 60);

        post_no.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        post_no.setForeground(new java.awt.Color(255, 255, 255));
        post_no.setBorder(javax.swing.BorderFactory.createTitledBorder("Post No."));
        post_no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                post_noActionPerformed(evt);
            }
        });
        jPanel1.add(post_no);
        post_no.setBounds(390, 130, 170, 60);

        l_name.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        l_name.setForeground(new java.awt.Color(255, 255, 255));
        l_name.setBorder(javax.swing.BorderFactory.createTitledBorder("LASTNAME"));
        l_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l_nameActionPerformed(evt);
            }
        });
        jPanel1.add(l_name);
        l_name.setBounds(210, 50, 170, 60);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 51, 51));
        jLabel5.setText("*Only if you have card");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(440, 210, 120, 15);

        age.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        age.setForeground(new java.awt.Color(255, 255, 255));
        age.setBorder(javax.swing.BorderFactory.createTitledBorder("AGE"));
        age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageActionPerformed(evt);
            }
        });
        jPanel1.add(age);
        age.setBounds(390, 50, 170, 60);

        address.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        address.setForeground(new java.awt.Color(255, 255, 255));
        address.setBorder(javax.swing.BorderFactory.createTitledBorder("ADDRESS"));
        address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressActionPerformed(evt);
            }
        });
        jPanel1.add(address);
        address.setBounds(30, 130, 170, 60);

        f_name.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        f_name.setForeground(new java.awt.Color(255, 255, 255));
        f_name.setBorder(javax.swing.BorderFactory.createTitledBorder("Firstname"));
        f_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f_nameActionPerformed(evt);
            }
        });
        jPanel1.add(f_name);
        f_name.setBounds(30, 50, 170, 60);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Signup");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(250, 0, 80, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/easypower/powerplant.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 600, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 601, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void f_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_f_nameActionPerformed

    private void addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressActionPerformed

    private void ageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageActionPerformed

    private void l_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_l_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_l_nameActionPerformed

    private void post_noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_post_noActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_post_noActionPerformed

    private void u_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_u_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_u_nameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try { 
           
           String url="jdbc:sqlserver://localhost:1433;databaseName=easypower;user=shitul;password=tnb";
           
           Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
           Connection con=DriverManager.getConnection(url);
           
           String sql_2 = "select u_name from users where u_name='"+u_name.getText()+"'";
           PreparedStatement pst_2=con.prepareStatement(sql_2);
           ResultSet rs = pst_2.executeQuery();
            if (rs.next()) {
                JOptionPane.showMessageDialog(null, "Username already taken. Please try another onle.");
            } else {
                if (!pass_1.getText().equals(pass_2.getText())) {
                    JOptionPane.showMessageDialog(null, "Password dosen't match with one another. Pleasr enter correctly");
                } else {
                    String sql= "INSERT INTO users"+"(f_name,l_name,age,address,post_no,u_name,pass_1,pass_2,u_type,cardholder,meter_number,balance,cardnumber)"+"values(?,?,?,?,?,?,?,?,?,?,?,0,?)";
                    PreparedStatement pst=con.prepareStatement(sql);
                    pst.setString(1,f_name.getText());
                    pst.setString(2,l_name.getText());
                    pst.setString(3,age.getText());
                    pst.setString(4,address.getText());
                    pst.setString(5,post_no.getText());
                    pst.setString(6,u_name.getText());
                    pst.setString(7,pass_1.getText());
                    pst.setString(8,pass_2.getText());
                    pst.setString(9,u_type.getSelectedItem().toString());
                    pst.setString(10,cardholder.getSelectedItem().toString());
                    pst.setString(11,meter_number.getText());
                    pst.setString(12,cardnumber.getText());
                
                    pst.executeUpdate();

                    new Login().setVisible(true);
                    this.setVisible(false);
                }
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(Signup.class.getName()).log(Level.SEVERE, null, ex);
             
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Signup.class.getName()).log(Level.SEVERE, null, ex);
        }
              
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new Login().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cardholderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardholderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cardholderActionPerformed

    private void cardholderItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cardholderItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cardholderItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Signup().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField address;
    private javax.swing.JTextField age;
    private javax.swing.JComboBox<String> cardholder;
    private javax.swing.JTextField cardnumber;
    private javax.swing.JTextField f_name;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField l_name;
    private javax.swing.JTextField meter_number;
    private javax.swing.JPasswordField pass_1;
    private javax.swing.JPasswordField pass_2;
    private javax.swing.JTextField post_no;
    private javax.swing.JTextField u_name;
    private javax.swing.JComboBox<String> u_type;
    // End of variables declaration//GEN-END:variables
}
